# Generated by Django 2.2.4 on 2020-07-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200623_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodVisitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('date', models.DateField(auto_now_add=True, verbose_name='访问的日期')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_counts', to='goods.GoodsCategory', verbose_name='分类')),
            ],
            options={
                'db_table': 'tb_goods_visit',
            },
        ),
    ]
